EasyCooking/Controllers/CategoryController.cs
using EasyCooking.Models;
using EasyCooking.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace EasyCooking.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IUserProfileRepository _userProfileRepository;
        public CategoryController(ICategoryRepository categoryRepository, IUserProfileRepository userProfileRepository)
        // GET: RecipeController
        {
            _categoryRepository = categoryRepository;
            _userProfileRepository = userProfileRepository;
        }
        // GET: CategoryController
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var ListCategory = _categoryRepository.GetAll();
            return View(ListCategory);
        }

        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            var category = _categoryRepository.GetCategoryById(id);
            return View(category);
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            int currentUserId = GetCurrentUserProfileId();
            UserProfile user = _userProfileRepository.GetById(currentUserId);
              if (user.UserTypeId == 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            try
            {
                _categoryRepository.CreateCategory(category);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryController/Edit/5
        public ActionResult Edit(int id)
        {
            Category category = _categoryRepository.GetCategoryById(id);
            return View(category);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Category category)
        {
            try
            {
                category.Id = id;
                _categoryRepository.Update(category);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(category);
            }

        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            var c = _categoryRepository.GetCategoryById(id);
            return View(c);
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            {
                try
                {
                    _categoryRepository.Delete(id);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    return View();
                }
            }
        }
        private int GetCurrentUserProfileId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
    }
}

EasyCooking/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using EasyCooking.Repositories;
using EasyCooking.Models;
using System.Collections.Generic;
using EasyCooking.Models.ViewModels;
using System.Security.Claims;
using System;
using Microsoft.AspNetCore.Authorization;
using System.Linq;

namespace EasyCooking.Controllers
{
    public class RecipeController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IRecipeRepository _recipeRepository;
        private readonly IIngredientRepository _ingredientRepository;
        private readonly IStepRepository _stepRepository;
        private readonly IUserProfileRepository _userProfileRepository;
        private readonly IFavoriteRepository _faoriteRepository;
        public RecipeController(IRecipeRepository recipeRepository, 
            ICategoryRepository categoryRepository, 
            IIngredientRepository ingredientRepository,
            IStepRepository stepRepository,
            IUserProfileRepository userProfileRepository,
            IFavoriteRepository favoriteRepository)
            
        // GET: RecipeController
            {
            _ingredientRepository = ingredientRepository;
            _categoryRepository = categoryRepository;
            _recipeRepository = recipeRepository;
            _stepRepository = stepRepository;
            _userProfileRepository = userProfileRepository;
            _faoriteRepository = favoriteRepository;
            }
        public ActionResult Index(string searching)
        {
            List<Recipe> recipes = _recipeRepository.GetAll();
            if (String.IsNullOrEmpty(searching))
            {
                return View(recipes);
            }
            else
            {
                return View(recipes.Where(x => x.CategoryName.Contains(searching) || searching == null).ToList());
            }
        }

        // GET: RecipeController/Details/5
        public ActionResult Details(int id)
        {
            var vm = new RecipeViewModel();
            vm.Recipe = _recipeRepository.GetById(id);
            vm.ingredients = _ingredientRepository.GetAllByRecipeId(id);
            vm.steps = _stepRepository.GetAllByRecipeId(id);
            ViewData["IsSubscribed"] = _faoriteRepository.IsSubscribed(GetCurrentUserProfileId(), id);
            if (vm.Recipe != null)
            {
                return View(vm);
            } 
            else
            {
                return NotFound();
            }
        }


        // GET: RecipeController/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var vm = new RecipeViewModel();
            vm.CategoryOptions = _categoryRepository.GetAll();
            return View(vm);
        }

        // POST: RecipeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecipeViewModel vm)
        {
            try
            {
                vm.Recipe.UserProfileId = GetCurrentUserProfileId();

                _recipeRepository.Add(vm.Recipe);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                vm.CategoryOptions = _categoryRepository.GetAll();
                return View(vm);
            }
        }

        // GET: RecipeController/Edit/5
        public ActionResult Edit(int id)
        {
            Recipe recipe = _recipeRepository.GetById(id);
            recipe.CategoryOptions = _categoryRepository.GetAll();
            ViewData["RecipeId"] = recipe.Id;
            return View(recipe);
        }

        // POST: RecipeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Recipe recipe)
        {
            try
            {

                _recipeRepository.UpdateRecipe(recipe);
                recipe.CategoryOptions = _categoryRepository.GetAll();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(recipe);
            }
        }

        // GET: RecipeController/Delete/5
        public ActionResult Delete(int id)
        {
            var recipe = _recipeRepository.GetById(id);
            int recipeId = recipe.Id;
            ViewData["RecipeId"] = recipeId;
            return View(recipe);
        }

        // POST: RecipeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Recipe recipe)
        {
            try
            {
                var getRecipeId = _recipeRepository.GetById(id);
                int recipeId = getRecipeId.Id;
                ViewData["RecipeId"] = recipeId;
                _recipeRepository.Remove(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        private int GetCurrentUserProfileId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
    }
}

EasyCooking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EasyCooking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Handlee&family=Roboto:wght@300&display=swap" rel="stylesheet">
    @RenderSection("Styles", required: false)
</head>
<body style="font-family:'Roboto'">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" style="font-family: 'Handlee'; font-size: 2rem;" asp-area="" asp-controller="Home" asp-action="Index">EasyCooking</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="Index">Recipe</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                        }
                        else
                        {
                            <li></li>
                        }
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid" style="padding-left: 0px; padding-right: 0px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2020 - EasyCooking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>