EasyCooking/Models/Recipe.cs
using System.Collections.Generic;


namespace EasyCooking.Models
{
    public class Recipe
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int UserProfileId { get; set; }
        public int? CategoryId { get; set; }
        public string ImageUrl { get; set; }
        public string VideoUrl { get; set; }
        public string Creator { get; set; }
        public string Description {get;set;}
        public int PrepTime { get; set; }
        public int CookTime { get; set; }
        public string ServingAmount { get; set; }
        public Category Category { get; set; }
        public string CategoryName { get; set; }
        public List<Category> CategoryOptions { get; set; }
        public string TotalTime
        {
            get
            {
                return $"{CookTime + PrepTime}";
            }
        }
    }
}

EasyCooking/Models/ViewModels/RecipeViewModel.cs
using System.Collections.Generic;

namespace EasyCooking.Models.ViewModels
{
    public class RecipeViewModel
    {
        public Recipe Recipe { get; set; }
        public Ingredient ingredient { get; set; }
        public Step step { get; set; }
        public Category category { get; set; }
        public List<Category> CategoryOptions { get; set; }
        public List<Ingredient> ingredients { get; set; }
        public List<Step> steps { get; set; }
    }
}

EasyCooking/Controllers/IngredientController.cs
using EasyCooking.Repositories;
using EasyCooking.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EasyCooking.Controllers
{
    public class IngredientController : Controller
    {
        private readonly IIngredientRepository _ingredientRepository;
        private readonly IRecipeRepository _recipeRepository;
        public IngredientController(IIngredientRepository ingredientRepository, IRecipeRepository recipeRepository)
        // GET: RecipeController
        {
            _ingredientRepository = ingredientRepository;
            _recipeRepository = recipeRepository;
        }
        // GET: IngredientController
        [HttpGet]
        public ActionResult Index(int id)
        {
            var ingredients = _ingredientRepository.GetAllByRecipeId(id);
            return View(ingredients);
        }

        // GET: IngredientController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        [HttpGet]
        // GET: IngredientController/Create
        public ActionResult Create(int id)
        {
            var recipe = _recipeRepository.GetById(id);
            ViewData["RecipeName"] = recipe.Title;
            ViewData["RecipeId"] = recipe.Id;
            return View();
        }

        // POST: IngredientController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, Ingredient ingredient)
        {
            try
            {
                ingredient.RecipeId = id;
                _ingredientRepository.Add(ingredient);
                return RedirectToAction("Details", "Recipe", new { id });
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: IngredientController/Edit/5
        public ActionResult Edit(int id)
        {
            Ingredient ingredient = _ingredientRepository.GetById(id);          
            return View(ingredient);
        }

        // POST: IngredientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Ingredient ingredient)
        {
            try
            {
                ingredient.Id = id;
                _ingredientRepository.UpdateIngredient(ingredient);
                return RedirectToAction("Details","Recipe", new { id = ingredient.RecipeId });
            }
            catch
            {
                return View();
            }
        }

        // GET: IngredientController/Delete/5
        public ActionResult Delete(int id)
        {
            var ingredient = _ingredientRepository.GetById(id);
            int recipeId = ingredient.RecipeId;
            ViewData["RecipeId"] = recipeId;
            return View(ingredient);
        }

        // POST: IngredientController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Ingredient ingredient)
        {
            try
            {
                var ingredientRecipeId = _ingredientRepository.GetById(id);
                int recipeId = ingredientRecipeId.RecipeId;
                ViewData["RecipeId"] = recipeId;
                _ingredientRepository.Remove(id);
                return RedirectToAction("Details", "Recipe", new { id = recipeId });
            }
            catch
            {
                return View();
            }
        }
    }
}

EasyCooking/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using EasyCooking.Repositories;
using EasyCooking.Models;
using System.Collections.Generic;
using EasyCooking.Models.ViewModels;
using System.Security.Claims;
using System;
using Microsoft.AspNetCore.Authorization;
using System.Linq;

namespace EasyCooking.Controllers
{
    public class RecipeController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IRecipeRepository _recipeRepository;
        private readonly IIngredientRepository _ingredientRepository;
        private readonly IStepRepository _stepRepository;
        private readonly IUserProfileRepository _userProfileRepository;
        private readonly IFavoriteRepository _faoriteRepository;
        public RecipeController(IRecipeRepository recipeRepository, 
            ICategoryRepository categoryRepository, 
            IIngredientRepository ingredientRepository,
            IStepRepository stepRepository,
            IUserProfileRepository userProfileRepository,
            IFavoriteRepository favoriteRepository)
            
        // GET: RecipeController
            {
            _ingredientRepository = ingredientRepository;
            _categoryRepository = categoryRepository;
            _recipeRepository = recipeRepository;
            _stepRepository = stepRepository;
            _userProfileRepository = userProfileRepository;
            _faoriteRepository = favoriteRepository;
            }
        public ActionResult Index(string searching)
        {
            List<Recipe> recipes = _recipeRepository.GetAll();
            if (String.IsNullOrEmpty(searching))
            {
                return View(recipes);
            }
            else
            {
                return View(recipes.Where(x => x.CategoryName.Contains(searching) || searching == null).ToList());
            }
        }

        // GET: RecipeController/Details/5
        public ActionResult Details(int id)
        {
            var vm = new RecipeViewModel();
            vm.Recipe = _recipeRepository.GetById(id);
            vm.ingredients = _ingredientRepository.GetAllByRecipeId(id);
            vm.steps = _stepRepository.GetAllByRecipeId(id);
            ViewData["IsSubscribed"] = _faoriteRepository.IsSubscribed(GetCurrentUserProfileId(), id);
            if (vm.Recipe != null)
            {
                return View(vm);
            } 
            else
            {
                return NotFound();
            }
        }


        // GET: RecipeController/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var vm = new RecipeViewModel();
            vm.CategoryOptions = _categoryRepository.GetAll();
            return View(vm);
        }

        // POST: RecipeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecipeViewModel vm)
        {
            try
            {
                vm.Recipe.UserProfileId = GetCurrentUserProfileId();

                _recipeRepository.Add(vm.Recipe);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                vm.CategoryOptions = _categoryRepository.GetAll();
                return View(vm);
            }
        }

        // GET: RecipeController/Edit/5
        public ActionResult Edit(int id)
        {
            Recipe recipe = _recipeRepository.GetById(id);
            recipe.CategoryOptions = _categoryRepository.GetAll();
            ViewData["RecipeId"] = recipe.Id;
            return View(recipe);
        }

        // POST: RecipeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Recipe recipe)
        {
            try
            {

                _recipeRepository.UpdateRecipe(recipe);
                recipe.CategoryOptions = _categoryRepository.GetAll();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(recipe);
            }
        }

        // GET: RecipeController/Delete/5
        public ActionResult Delete(int id)
        {
            var recipe = _recipeRepository.GetById(id);
            int recipeId = recipe.Id;
            ViewData["RecipeId"] = recipeId;
            return View(recipe);
        }

        // POST: RecipeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Recipe recipe)
        {
            try
            {
                var getRecipeId = _recipeRepository.GetById(id);
                int recipeId = getRecipeId.Id;
                ViewData["RecipeId"] = recipeId;
                _recipeRepository.Remove(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        private int GetCurrentUserProfileId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
    }
}

EasyCooking/Controllers/StepController.cs
using EasyCooking.Models;
using EasyCooking.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EasyCooking.Controllers
{
    public class StepController : Controller
    {
        private readonly IIngredientRepository _ingredientRepository;
        private readonly IRecipeRepository _recipeRepository;
        private readonly IStepRepository _stepRepository;
        public StepController(IStepRepository stepRepository, IIngredientRepository ingredientRepository, IRecipeRepository recipeRepository)
        // GET: RecipeController
        {
            _ingredientRepository = ingredientRepository;
            _recipeRepository = recipeRepository;
            _stepRepository = stepRepository;
        }
        // GET: StepController
        public ActionResult Index(int id)
        {
            var steps = _stepRepository.GetAllByRecipeId(id);
            return View(steps);
        }

        // GET: StepController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: StepController/Create
        public ActionResult Create(int id)
        {
            var recipe = _recipeRepository.GetById(id);
            ViewData["RecipeName"] = recipe.Title;
            ViewData["RecipeId"] = recipe.Id;
            return View();
        }

        // POST: StepController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, Step step)
        {
            try
            {
                step.RecipeId = id;
                _stepRepository.Add(step);
                return RedirectToAction("Details", "Recipe", new { id });
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: StepController/Edit/5
        public ActionResult Edit(int id)
        {
            Step step = _stepRepository.GetById(id);
            return View(step);
        }

        // POST: StepController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Step step)
        {
            try
            {
                step.Id = id;
                _stepRepository.UpdateStep(step);
                return RedirectToAction("Details", "Recipe", new { id = step.RecipeId });
            }
            catch
            {
                return View();
            }
        }

        // GET: StepController/Delete/5
        public ActionResult Delete(int id)
        {
            var step = _stepRepository.GetById(id);
            int recipeId = step.RecipeId;
            ViewData["RecipeId"] = recipeId;
            return View(step);
        }

        // POST: StepController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Step step)
        {
            try
            {
                var stepRecipeId = _stepRepository.GetById(id);
                int recipeId = stepRecipeId.RecipeId;
                ViewData["RecipeId"] = recipeId;
                _stepRepository.Remove(id);
                return RedirectToAction("Details", "Recipe", new { id = recipeId });
            }
            catch
            {
                return View();
            }
        }
    }
}

EasyCooking/Views/Recipe/Create.cshtml
@model EasyCooking.Models.ViewModels.RecipeViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Recipe.Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Recipe.Title" class="control-label"></label>
                <input asp-for="Recipe.Title" class="form-control" />
                <span asp-validation-for="Recipe.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Recipe.UserProfileId" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Recipe.CategoryId" class="control-label"></label>
                <select asp-for="Recipe.CategoryId" class="form-control">
                    @foreach (var category in Model.CategoryOptions)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="Recipe.CategoryId" class="text-danger"></span>
            </div>
                <div class="form-group">
                    <label asp-for="Recipe.ImageUrl" class="control-label"></label>
                    <input asp-for="Recipe.ImageUrl" class="form-control" />
                    <span asp-validation-for="Recipe.ImageUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Recipe.VideoUrl" class="control-label"></label>
                    <input asp-for="Recipe.VideoUrl" class="form-control" />
                    <span asp-validation-for="Recipe.VideoUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Recipe.Creator" class="control-label"></label>
                    <input asp-for="Recipe.Creator" class="form-control" />
                    <span asp-validation-for="Recipe.Creator" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Recipe.Description" class="control-label"></label>
                    <input asp-for="Recipe.Description" class="form-control" />
                    <span asp-validation-for="Recipe.Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Recipe.PrepTime" class="control-label"></label>
                    <input asp-for="Recipe.PrepTime" class="form-control" />
                    <span asp-validation-for="Recipe.PrepTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Recipe.CookTime" class="control-label"></label>
                    <input asp-for="Recipe.CookTime" class="form-control" />
                    <span asp-validation-for="Recipe.CookTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Recipe.ServingAmount" class="control-label"></label>
                    <input asp-for="Recipe.ServingAmount" class="form-control" />
                    <span asp-validation-for="Recipe.ServingAmount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
</form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EasyCooking/Views/Recipe/Delete.cshtml
@model EasyCooking.Models.Recipe

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Recipe" asp-action="Details" asp-route-id="@ViewData["RecipeId"]">Back to List</a>
    </form>
</div>

EasyCooking/Views/Recipe/Details.cshtml
@model EasyCooking.Models.ViewModels.RecipeViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="d-flex justify-content-center flex-lg-row flex-md-column flex-sm-column ">
    <div class="image-box-details">
        @if (Model.Recipe.VideoUrl == null)
        {
            <img src="@Model.Recipe.ImageUrl" alt="Photo of Food" />
        }
        else
        {
            <iframe width="100%"
                    height="100%"
                    src="@Model.Recipe.VideoUrl"
                    title="YouTube video player"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowFullScreen 
                    ></iframe>
        }
    </div>
    <div class="description d-flex flex-column">
        <div>
            <h2>@Model.Recipe.Title</h2>
            <p>By: @Model.Recipe.Creator</p>
            <p>@Model.Recipe.Description</p>
        </div>
        <div style="padding-top: 50px;">
            <img src="~/Icons/icons8-facebook.svg" alt="Group Logo" /> 
            <img src="~/Icons/icons8-pinterest.svg" alt="Instagram Logo" />
            <img src="~/Icons/icons8-twitter-circled.svg" alt="Pintrest Logo" /> 
            <img src="~/Icons/icons8-instagram.svg" alt="Twitter Logo" /> 
        </div>
    </div>
    <div>
        <h4>Meal Info</h4>
        <div class="border rounded p-3">
            <ul class="list-unstyled">
                <li class="pb-2">Prep Time: @Model.Recipe.PrepTime</li>
                <li class="pb-2">Cook Time: @Model.Recipe.CookTime</li>
                <li class="pb-2">Total: @Model.Recipe.TotalTime</li>
                <li>Serves: @Model.Recipe.ServingAmount</li>
            </ul>
        </div>
    </div>
</div>

<div>
    <div class="div2">
        <div>
            <div class="d-flex justify-content-around pt-4">
                <h2>Ingredients</h2>
                @if (!(bool)ViewData["IsSubscribed"])
                {
                    var actionUrl = $"/Favorites/Create/{Model.Recipe.Id}";
                    <form action=@actionUrl method="get">
                        <input type="submit" id="btnSend" value="Favorite" />
                    </form>
                }
                else
                {
                    var actionUrl = $"/Favorites/Delete/{Model.Recipe.Id}";
                    <form action=@actionUrl method="get">
                        <input type="submit" id="btnSend" value="Unfavorite" />
                    </form>
                }
            </div>
            @if (User.IsInRole("Admin"))
            {
                <a asp-controller="Ingredient" asp-action="Create" asp-route-id="@Model.Recipe.Id"><input class="input-button" type="button" value="Add Ingredient" /></a>
            }
            else
            {
                <div></div>
            }
        </div>
        <table  class="ingredients-table">
            <tbody >
                @foreach (var item in Model.ingredients)
                {
                    <tr>
                        <td class="pb-2 pt-2 ">
                            @Html.DisplayFor(modelItem => item.Content)
                        </td>
                        @if (User.IsInRole("Admin"))
                        {
                            <td>
                                @Html.ActionLink("Edit", "Edit", "Ingredient", new { id = item.Id }) |
                                @Html.ActionLink("Delete", "Delete", "Ingredient", new { id = item.Id })
                            </td>
                        }
                        else
                        {

                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="div3">
        <div class="d-flex justify-content-around pt-4">
            <h2 class="directions-h1">Directions</h2>
            @if (User.IsInRole("Admin"))
            {
                <a asp-controller="Step" asp-action="Create" asp-route-id="@Model.Recipe.Id"><input class="mb-2" type="button" value="Add a Step" /></a>
            }
            else
            {
                <div></div>
            }
        </div>
        <div class="direction-table">
            <ol>
                @foreach (var item in Model.steps)
                {
                    <li>
                        <p>
                            @Html.DisplayFor(modelItem => item.Content)

                            @if (User.IsInRole("Admin"))
                            {
                                @Html.ActionLink("Edit |", "Edit", "Step", new { id = item.Id })
                                @Html.ActionLink(" Delete", "Delete", "Step", new { id = item.Id })
                            }
                            else
                            {
                                <div></div>
                            }
                        </p>
                    </li>
                }
            </ol>
        </div>
    </div>
</div>

    </dl>
<div>
    <div class="d-flex justify-content-around">
        <div>
        @if (User.IsInRole("Admin"))
        {
            <a asp-action="Edit" asp-route-id="@Model.Recipe.Id" class="btn btn-outline-primary mx-1" title="Edit">
                
            </a>
            <a asp-action="Delete" asp-route-id="@Model.Recipe.Id" class="btn btn-outline-primary mx-1" title="Delete">
                
            </a>
        }
        else
        {
            <div></div>
        }
            </div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>
</div>

EasyCooking/Views/Recipe/Edit.cshtml
@model EasyCooking.Models.Recipe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="UserProfileId" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.CategoryOptions)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VideoUrl" class="control-label"></label>
                <input asp-for="VideoUrl" class="form-control" />
                <span asp-validation-for="VideoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creator" class="control-label"></label>
                <input asp-for="Creator" class="form-control" />
                <span asp-validation-for="Creator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrepTime" class="control-label"></label>
                <input asp-for="PrepTime" class="form-control" />
                <span asp-validation-for="PrepTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CookTime" class="control-label"></label>
                <input asp-for="CookTime" class="form-control" />
                <span asp-validation-for="CookTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServingAmount" class="control-label"></label>
                <input asp-for="ServingAmount" class="form-control" />
                <span asp-validation-for="ServingAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Recipe" asp-action="Details" asp-route-id="@ViewData["RecipeId"]">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EasyCooking/Views/Recipe/Index.cshtml
@model IEnumerable<EasyCooking.Models.Recipe>

@{
    ViewData["Title"] = "Index";
}


<div class="d-flex justify-content-around pt-4">
    <h1 style="text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">Explore New Recipies!</h1>
    <div>
        @using (Html.BeginForm("Index", "Recipe", FormMethod.Get))
        {
            <div class="d-flex flex-row">
                @Html.TextBox("searching")<input style="color: black;" placeholder="Category..." type="submit" value="Search" />
                <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="Index">Reset</a>
            </div>
        }
    </div>
    @if (User.IsInRole("Admin"))
    {
<div>
    <a asp-action="Create">Add New Recipe</a>

</div>
    }
    else
    {
        <div></div>
    }
    <div>
        <p></p>
    </div>
</div>
<div id="cards_landscape_wrap-2">
    <div class="container">
        <div id="cards_landscape_wrap-2">
            <div class="row">
                @if (Model.Count() == 0)
                {
                    <tr>
                        <td colspan="3">
                            No Matches Found
                        </td>
                    </tr>
                }

                else
                {
                    @foreach (var item in Model)
                    {
                        {var actionUrl = $"Favorites/Create/{item.Id}";}
                        <div class="col-sm-12 col-md-6 col-lg-3">
                            <a asp-action="Details" asp-route-id="@item.Id" class="text-decoration-none text-body">
                                <div class="card-flyer">
                                    <div class="text-box">
                                        <div class="image-box">
                                            <img src="@item.ImageUrl" alt="" />
                                        </div>
                                        <div class="text-container">
                                            <h6>@item.Title</h6>
                                            <p>By: @item.Creator</p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>